source 'https://rubygems.org'

gem 'sinatra'
gem 'telegram-bot-ruby', '~> 0.8.6.1'
gem 'httparty', '0.14.0'
gem 'dotenv', '~> 2.1', '>= 2.1.1'
gem 'rspec', '~> 3.5'
gem 'rake', '12.1.0'
gem 'logging', '~> 2.2', '>= 2.2.2'
gem 'logstash-logger'
gem 'net-ssh', '~> 4.2'
gem 'rest-client'
gem 'racksh'
gem 'pry'
