squads:
  smoke-testing-bbm:
    - "mpermperpisang"
    - "amananm513"
  smoke-testing-btp:
    - "Fathirw"
  smoke-testing-chat:
    - "dickyedg"
  smoke-testing-csi:
    - "Mirzaaditya"
  smoke-testing-dgt:
    - "arisnugraha"
  smoke-testing-inv:
    - "andimryn"
  smoke-testing-mwc:
    - "tinusagustin"
  smoke-testing-notif:
    - "yudadul"
  smoke-testing-pcv:
    - "irfanharies"
  smoke-testing-pnl:
    - "Yudhamau"
  smoke-testing-pnr:
    - "olvilora"
    - "Lamhotjm"
  smoke-testing-polseq:
    - "ariyohendrawan"
  smoke-testing-px:
    - "ajengfujii"
  smoke-testing-rev:
    - "WiraPramudy"
  smoke-testing-sct:
    - "jassire"
  smoke-testing-seo:
    - "tinusagustin"
  smoke-testing-shg:
    - "fauridhomahran"
    - "luthfiswees"
  smoke-testing-uts:
    - "ariyohendrawan"
  smoke-testing-vp-postpaid:
    - "arsoedjono"
  smoke-testing-vp-prepaid:
    - "Fadhlimaulidri"
  smoke-testing-vp-ticketing:
    - "rizkyandika88"
  smoke-testing-xpress:
    - "ferie993"
exclude:
  - smoke-testing-sct
  - smoke-testing-fintech
